#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running pre-commit hooks"

echo "Running tests..."
yarn run test

echo "Running eslint..."
yarn run eslint

echo "Running prettier..."
yarn run pretty-check