#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running pre-commit hooks"

echo "Running tests..."
yarn run test

echo "Running eslint with lint-staged..."
yarn run lint-staged

echo "Running prettier..."
yarn run pretty-check

echo "Running svelte-checks..."
yarn run svelte-check