name: CD

on:
  # Can run on command
  workflow_dispatch:
  # Runs on pushes to master branch
  push:
    branches: [master]

jobs:
  build:
    uses: ./.github/workflows/ci.yml
  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
  smoke:
    needs: deploy
    uses: ./.github/workflows/smoke.yml
