name: CI

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: [master]

jobs:
  build:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "24"
      - name: Install pnpm
        uses: pnpm/action-setup@v6
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Cache pnpm dependencies
        uses: actions/cache@v6
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm run lint
      - name: Test
        run: pnpm run test
      - name: Build application
        run: pnpm run build
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@642ef024cc554a34b7082cea12c7bf63575ae151 # v1.0.36
        with:
          title: "Unit Test Coverage Report"
          junitxml-path: ./test-results.xml
          junitxml-title: Unit Test Report
      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: build
          path: .next/
          retention-days: 7
