name: CI

on:
  # Can run on command
  workflow_dispatch:
  # Can be run by other actions
  workflow_call:
  # Runs on pull requests
  pull_request:
    branches: [master]

jobs:
  build:
    name: build-and-test
    # Running on ubuntu-latest, nothing special
    runs-on: ubuntu-latest
    steps:
      # As usual, we simply checkout the project
      - name: Checkout
        uses: actions/checkout@v4
      # Setup the latest version of Bun
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      # Install project dependencies
      - name: Install dependencies
        run: bun install --frozen-lockfile
      # Make sure the application can build
      - name: Build application
        run: bun run build
      # Now we run our tests
      - name: Run tests
        run: bun run test
      # This comments the current Jest Coverage Report containing JUnit XML reports and a Code Coverage Summary
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@434e6d2d37116d23d812809b61d499639842fa3b # v1.0.26
        with:
          title: "Unit Test Coverage Report"
          junitxml-path: ./test-results.xml
          junitxml-title: Unit Test Report
